# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class State(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, state: bool=None):
        """
        State - a model defined in Swagger

        :param state: The state of this State.
        :type state: bool
        """
        self.swagger_types = {
            'state': bool
        }

        self.attribute_map = {
            'state': 'state'
        }

        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'State':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The State of this State.
        :rtype: State
        """
        return deserialize_model(dikt, cls)

    @property
    def state(self) -> bool:
        """
        Gets the state of this State.

        :return: The state of this State.
        :rtype: bool
        """
        return self._state

    @state.setter
    def state(self, state: bool):
        """
        Sets the state of this State.

        :param state: The state of this State.
        :type state: bool
        """

        self._state = state

